import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import F1CarAnimation from "./components/F1CarAnimation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: "Arial" }}>
        <nav style={{
          background: "#111",
          color: "white",
          padding: "15px",
          display: "flex",
          justifyContent: "space-between"
        }}>
          <h2>🏎 Speed Track</h2>
          <div style={{ display: "flex", gap: "20px" }}>
            <a href="/">Home</a>
            <a href="/standings" style={{color: "white",textDecoration:"none"}}>Standings</a>
            <a href="/news" style={{color: "white",textDecoration:"none"}}>News</a>
            <a href="/guide" style={{color: "#FF1801", fontWeight: "bold", textDecoration:"none"}}>Beginner's Guide</a>
          </div>
        </nav>

        <div style={{ padding: "20px" }}>
          {children}
        </div>
        <F1CarAnimation />
      </body>
    </html>
  );
}


